#include "SakanX/Admin.h"
#include <iostream>


using namespace std;

Admin::Admin(const string& name, int id, const string& ssn, int age, const string& department)
    : Person(name, id,ssn,age), department(department), studentsManaged(0) {
}

Admin::Admin(const string& name, int id, const string& ssn, int age, 
             NationalityType nationality, const string& department,
             const vector<pair<string, string>>& contacts)
    : Person(name, id,ssn,age,nationality,contacts), department(department), studentsManaged(0) {}
//               Getters
string Admin::getDepartment() const {
    return department;
}

int Admin::getNumOfStudentsManaged() const {
    return studentsManaged;
}   

//               Setters
void Admin::setDepartment(const string& newDepartment) {
    department = newDepartment;
}



//                  Admin Privileges

void Admin::assignStudentToApartment(Student* student, Apartment* apartment) {
    if (student == nullptr || apartment == nullptr) {
        cout << "Error: Invalid student or apartment!\n";
        return;
    }
    
    apartment->addStudent(student);
    studentsManaged++;
    
    cout << "Admin " << name << " assigned student to apartment.\n";
}

void Admin::removeStudentFromApartment(Student* student, Apartment* apartment) {
    if (student == nullptr || apartment == nullptr) {
        cout << "Error: Invalid student or apartment!\n";
        return;
    }
    
    // You'll need to add removeStudent() method to Apartment class
    apartment->removeStudent(student);
    studentsManaged--;
    
    cout << "Admin " << name << " removed student from apartment.\n";
}

void Admin::transferStudent(Student* student, Apartment* from, Apartment* to) {
    cout << "Admin " << name << " transferring student...\n";
    
    removeStudentFromApartment(student, from);
    assignStudentToApartment(student, to);
    
    cout << "Transfer completed successfully!\n";
}

void Admin::viewAllApartments(const vector<Apartment*>& apartments) const {
    cout << "=== Apartment Overview by Admin " << name << " ===\n";
    cout << "Total Apartments: " << apartments.size() << "\n\n";
    
    for (int i = 0; i < apartments.size(); i++) {
        cout << "Apartment #" << (i + 1) << ":\n";
        apartments[i]->displayApartmentInfo();
        cout << "------------------------\n";
    }
}

// Calculate total revenue from all apartments
void Admin::calculateTotalRevenue(const vector<Apartment*>& apartments) const {
    cout << "\n=== Total Revenue Report ===\n";
    cout << "Generated by Admin: " << name << "\n\n";
    
    double totalRevenue = 0.0;
    int occupiedCount = 0;
    
    for (int i = 0; i < apartments.size(); i++) {
        double rent = apartments[i]->getRentPrice();
        int students = apartments[i]->getCurrentTenants();
        
        if (students > 0) {
            totalRevenue += rent;
            occupiedCount++;
            cout << "Apartment #" << (i + 1) << ": " << rent << " EGP\n";
        }
    }
    
    cout << "\nOccupied Apartments: " << occupiedCount << "\n";
    cout << "Total Monthly Revenue: " << totalRevenue << " EGP\n";
    cout << "Annual Revenue: " << (totalRevenue * 12) << " EGP\n";
    cout << "================================\n\n";
}

void Admin::displayInfo() const 
{
    cout << "\n========================================\n";
    cout << "         ADMIN INFORMATION\n";
    cout << "========================================\n";
    cout << "Name         : " << name << "\n";
    cout << "ID           : " << id << "\n";
    
    if (!ssn.empty()) 
        cout << "SSN          : " << ssn << "\n";
    
    cout << "Age          : " << age << "\n";
    cout << "Department   : " << department << "\n";
    cout << "Students Managed: " << studentsManaged << "\n";
    
    if (!contacts.empty()) 
    {
        cout << "\n--- Contact Information ---\n";
        for (const auto& contact : contacts) 
            cout << "  " << contact.first << ": " << contact.second << "\n";

    }
}
Admin::~Admin() {
}